extraction:
  cpp:
    prepare:
      packages:
        - qt5-default
        - libqt5sql5-sqlite
        - qtdeclarative5-dev
        - qml-module-qtquick2
        - qml-module-qtquick-controls
        - libssl-dev
    after_prepare:
      - pwd
      - wget https://swift.im/downloads/releases/swift-4.0.2/swift-4.0.2.tar.gz
      - tar -xf swift-4.0.2.tar.gz
      - cd swift-4.0.2
      - sed -i -E "s/(env\[\"BOOST_BUNDLED\"\] = True)/\1\n\1/" BuildTools/SCons/SConstruct
      - sed -i -E "s/(env\[\"EXPAT_BUNDLED\"\] = True)/\1\n\1/" BuildTools/SCons/SConstruct
      - ./scons Swiften
    configure:
      command:
        - pwd
        - git clone https://github.com/gkdr/libomemo 
        - cd libomemo && git checkout tags/v0.7.0 && make && cd ..
        - git clone https://github.com/gkdr/axc
        - cd axc && git checkout tags/v0.3.3 && git submodule update --init && make
        - cd lib/libsignal-protocol-c/ && mkdir build && cd build && cmake .. && make && cd ../../../..
        - mkdir _lgtm_build_dir
        - cd _lgtm_build_dir
        - qmake .. DEFINES+=TRAVIS

