@startuml
skinparam packageStyle rectangle

[GUI]
[Client]
[Qt] <<library>>
[Swiften] <<library>>
[libomemo] <<library>>
[axc] <<library>>

[GUI] -- [Client]
[Client] -- [Qt]
[Client] -- [Swiften]
[Client] - [libomemo]
[libomemo] - [axc]

@enduml

