@startuml
[ChatMarkers] --> [RosterController]
[ChatMarkers] --> [Persistence]
[ChatMarkers] --> [XmlWriter]
[ConnectionHandler] --> [ReConnectionHandler]
[ConnectionHandler] --> [IpHeartBeatWatcher]
[ConnectionHandler] --> [XmppPingController]
[DiscoInfoHandler] --> [HttpFileUploadManager]
[FileModel] --> [FileInfo]
[GcmController] --> [Database]
[HttpFileUploadManager] --> [XmlHttpUploadContentHandler]
[HttpFileUploadManager] --> [HttpFileUploader]
[MessageController] --> [Database]
[MessageHandler] --> [Persistence]
[MessageHandler] --> [DownloadManager]
[MessageHandler] --> [Settings]
[MessageHandler] --> [ChatMarkers]
[MucManager] --> [XmlWriter]
[MucManager] --> [MucCollection]
[Persistence] --> [GcmController]
[Persistence] --> [MessageController]
[PresenceHandler] --> [RosterController]
[RosterController] --> [PresenceHandler]
[RosterController] --> [RosterItem]
[SessionController] --> [Database]
[Shmoose] --> [Persistence]
[Shmoose] --> [ConnectionHandler]
[Shmoose] --> [MessageHandler]
[Shmoose] --> [Settings]
[Shmoose] --> [RosterController]
[Shmoose] --> [HttpFileUploadManager]
[Shmoose] --> [DiscoInfoHandler]
[Shmoose] --> [MucManager]
@enduml

