[[section-quality-scenarios]]
== Quality Requirements and Quality Tree

Refer to 1.2. Quality Goals. This goals will not be detailed any more.

=== Quality Scenarios

Pre-Condition: If not otherwise stated, all the described scenarios are online-scenarios.

Reliability::

A user wants to send a message to one of his contacts. After composing and sending the message, the status of that message is displayed within 5 seconds.

Security::

A user wants to send a message to an other client, which also implements OMEMO E2E Security. After detecting that the other client also supports OMEMO, the client switches automatically to the use of OMEMO Security. This security feature is shown to the user within 2 Seconds.

A user receives an OMEMO encrypted message from an other client. If that messages was altered in any way, which breaks the integrity of that message, a security alterd must be shown to the user within 1 second. 

Modularity::

A developer wants to add additional functionality to the client. The developer is able to implement the majority of the code in a separate module. The amount of changes to other code parts of the client is limited to instantiation of that module with the needed dependencies achieved by injection.

Portability::

A developer wants to port the client to an other operating system. The additional effort is limited to the GUI part with some needed adaptions for the system integration.

