name: build_shmoose

on: 
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    #runs-on: ubuntu-16.04

    steps:
    #- name: Checkout
    #  uses: actions/checkout@v1

    #- name: Install Qt
    #  uses: jurplel/install-qt-action@v2

    - name: Install additional packages
      continue-on-error: true
      run: |
         #sudo systemctl unmask epmd.socket # for ejabberd to get installed
         #sudo apt-get install asciidoctor plantuml graphviz lcov ejabberd
         sudo apt install ejabberd

    - name: dump errors
      continue-on-error: true
      run: |
       #sudo journalctl -xe
       sudo tail -n 200 /var/log/syslog
       sudo tail -n 200 /var/log/dpkg.log

#    - name: Install swift lib
#      run: |
#         wget --no-check-certificate -q https://swift.im/downloads/releases/swift-4.0.2/swift-4.0.2.tar.gz
#         tar -xf swift-4.0.2.tar.gz
#         cd swift-4.0.2
#         /bin/bash scons -j 4 Swiften

#    - name: build shmoose x86
#      run: |
#          mkdir -p buildx86
#          cd buildx86
#          qmake .. DEFINES+=TRAVIS
#          make

#    - name: run test
#      run: ./scripts/travis/testing.sh

