name: build_shmoose

on: 
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install Qt
      uses: jurplel/install-qt-action@v

    - name: Install swift lib
      run: |
         wget --no-check-certificate -q https://swift.im/downloads/releases/swift-4.0.2/swift-4.0.2.tar.gz
         tar -xf swift-4.0.2.tar.gz
         cd swift-4.0.2
         /bin/bash scons -j 4 Swiften

